// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYhV41GdlRPNjZQc5LWvwcVV52-Y3VKOE',
    appId: '1:260359240000:android:963d98f003e2798ab9a2a5',
    messagingSenderId: '260359240000',
    projectId: 'melodica-customer-self-service',
    storageBucket: 'melodica-customer-self-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWD7bwfpBGImKMR6NntqBsVeOhpN-yxdQ',
    appId: '1:260359240000:ios:fa01ff1bb95c30f3b9a2a5',
    messagingSenderId: '260359240000',
    projectId: 'melodica-customer-self-service',
    storageBucket: 'melodica-customer-self-service.appspot.com',
    androidClientId: '260359240000-78j4bgrqqu9gau64261afm0gtpdvqoaf.apps.googleusercontent.com',
    iosClientId: '260359240000-uutgnp2laejffq850vgsnrg3da9ku2vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.melodicaAppNew',
  );
}
